language: java
jdk:
- oraclejdk8
script: mvn clean verify
deploy:
  provider: releases
  api_key:
    secure: AMTvq22Of0G8U3GzskY3PxcB+VGmtJGFjRzmDF3GrEnJp+d8kDJWTWMRPe46RXwTBAN5U9jytIV7C8nL+nzPylW3tiGXairidEWEP8E010wCd7jChJujSfCTqsVmeNdKI3FLUlQdUaNq0Od0NP0aFJmEWJSp4qDEzPTKv24VZ9VDN624l5mNs+3PnjSFCPudhrx9q4Wz9eywv/GiSoZPTxQdD/uYKD7zB5Y2IhNy38+OIuE7iLHm4swUtTBYyRoagtWKx9QOWHHSe84Gtt/uSItMpyaQQ+brNf4RTIyzc2b7MLA53/4vZeuh47MTuctMS80vpqWIpW9UyclYNqzn8/nJQLZVyufDH7LF56Ic+wymiMKTAC7nkPFqxb3Sk8tfaRZZu1/1BErjBJ2wEpGmm50n+Vn1mKRTdK7BBRSr5axQj0vy8B3oiANfF+KdRwe4Y9sljD46zFaFiQZ0uaruYDjQ2j0/nhBJycQX7tUyeoXAovg8nfCN287hloJd3rCy/JZ6qtegWsZFnqKpz/QsyF3csu6P8pXkqxHJNaOq1K+fleZrgz8uZzsae6+FY0WuuY5/XMFmTEu2DnB1o05RLlGkEeoz79apO3ziEm3MZuu2VWyTLo0KvbG7Qzppb3McJbYU2BLzCiP0OuFM+CUTMTLzu6/evBtxAC40393k0p8=
  file: "./flightsearch/target/specs/com/rmb/flightsearch/specs/SimpleFlightSearch.html"
  on:
    repo: agseijas/bdd-flightsearch
